language: node_js
node_js:
- '0.12'
notifications:
  slack:
    secure: WjYEu3fdrBS8c4TsHlhFwm49UmmysxfIz7Sfk5Pz4fqWUrT2699v4Y0KVZAqSiZ+rlNUBipWyfP+c95HJ7L3ks3YAMXOvF50TbhJmICkIX7C6sNnz+SU4D5ByTgac4bsXHMiQsOojDnyeikgCg+Wiub+JToqdQ6rIAlMddRUMlGwRF061bXNgUPtmo/ZU2B519OL0+qRha+/bfpgskgIZvu/eJW5BpxqewkqBnUq/GnHJgdpC70BDSB2y0zhTFLBpoo2LnpvoayEfQ0mdkyu2on2i6kws9iQrfxh2JwiEIMfMxp83UA4HDzBxZk1urC2vdNIKYyIaiQylMCahBM94eBHH7wsklXVQkpL9RkvYvwatdyu0gd0g7ia4MprDqySUnowv7OoksrgMIi5rHirz6Ujce9oXezQr1BtCZ6xbKc5J6gBnq8OFnO1Sc/VWdgUBINi4F68kquuhMwXzpdR8d5VjccwgeZ5t+yT7pJ7gqOdEX1hDNqaZckygKucpLbW2bhXvo1YNCVV7OWwfk8z3YY/0UY1Ahi5UDQDq1gbbb1qdtEMz2/6xaK82Ue7FvOYz3sDUJX51Z5tVMoC8ZByAh0qvSGGH4/ZWRKuuhLL1+YCvQKu1qNu07hjRppZdP0z5kXJ7xmNRVkIISxMXB10abYgr8ywVXtGE/iUZHBEPpo=
